In [1]:
import os
import sys

import pandas as pd
import numpy as np
import catboost
np.set_printoptions(precision=4)
from catboost import *
from catboost import datasets
from catboost import CatBoostClassifier
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok


In [2]:
w = catboost.MetricVisualizer('catboost_info\\')
w.start()

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [105]:
from catboost.datasets import titanic
import numpy as np

train_df = pd.read_csv("grades.csv")

train_df.head()

PUPIL_SEX PUPIL_CLASS  TEACHER_RIGHT  TEACHER_CHK  TEACHER_QUEST  \
0         F          8A             65            0              4   
1         F          8A             70            4              0   
2         F          8A             85            0              0   
3         M          8A             55            0              0   
4         M          8A             40            1              2   

   TEACHER_CORR  PUPIL_CORR  PUPIL_STRIP GRADE  
0             2           1            6    4-  
1             4           0            4     3  
2             4           3            5     4  
3             1           8            3     3  
4             0           3            4     2

In [106]:
null_value_stats = train_df.isnull().sum(axis=0)
null_value_stats[null_value_stats != 0]

Series([], dtype: int64)

In [107]:
train_df.fillna(-999, inplace=True)

In [108]:
X = train_df.drop('GRADE', axis=1)
y = train_df.GRADE

In [109]:
print(X.dtypes)

categorical_features_indices = np.where(X.dtypes != float)[0]

PUPIL_SEX        object
PUPIL_CLASS      object
TEACHER_RIGHT     int64
TEACHER_CHK       int64
TEACHER_QUEST     int64
TEACHER_CORR      int64
PUPIL_CORR        int64
PUPIL_STRIP       int64
dtype: object


In [110]:
from sklearn.model_selection import train_test_split

X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.75, random_state=42)


In [111]:
from catboost import CatBoostClassifier, Pool, metrics, cv
from sklearn.metrics import accuracy_score

In [112]:
for i in [50, 60, 70, 80, 90, 100]:
    model = CatBoostClassifier(
        iterations=100,
        random_seed=i,
        logging_level='Silent',
        eval_metric=metrics.Accuracy()
    )
    model.fit(
        X_train, y_train,
        cat_features=categorical_features_indices,
        eval_set=(X_validation, y_validation),
    #     logging_level='Verbose',  # you can uncomment this for text output
        plot=True,
    );

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [73]:
model.fit(
    X_train, y_train,
    cat_features=categorical_features_indices,
    eval_set=(X_validation, y_validation),
#     logging_level='Verbose',  # you can uncomment this for text output
    plot=True
);

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [15]:
predictions = model.predict(X_validation)
predictions_probs = model.predict_proba(X_validation)
print(predictions[:10])
print(predictions_probs[:10])

[['3']
 ['4']
 ['4']
 ['4']
 ['4']
 ['3']
 ['5-']
 ['5-']
 ['4']
 ['5']]
[[0.157  0.6081 0.0259 0.0747 0.0734 0.0267 0.0342]
 [0.0918 0.1162 0.0166 0.5755 0.055  0.1075 0.0374]
 [0.1045 0.1638 0.0187 0.4735 0.1302 0.0335 0.0758]
 [0.1204 0.1948 0.0509 0.3309 0.1324 0.0341 0.1364]
 [0.1602 0.2725 0.0359 0.3291 0.0757 0.0758 0.0508]
 [0.1678 0.2727 0.1582 0.2652 0.0532 0.0312 0.0518]
 [0.0151 0.037  0.0133 0.0909 0.0297 0.0667 0.7473]
 [0.0147 0.0272 0.0125 0.0899 0.0216 0.085  0.7492]
 [0.0895 0.2538 0.029  0.3781 0.1347 0.0423 0.0726]
 [0.0299 0.0245 0.0167 0.0358 0.015  0.8341 0.0439]]


In [98]:
train_df = pd.read_csv("Starbucks satisfactory survey.csv")

train_df.head()

Timestamp 1. Your Gender    2. Your Age  \
0  2019/10/01 12:38:43 PM GMT+8         Female  From 20 to 29   
1  2019/10/01 12:38:54 PM GMT+8         Female  From 20 to 29   
2  2019/10/01 12:38:56 PM GMT+8           Male  From 20 to 29   
3  2019/10/01 12:39:08 PM GMT+8         Female  From 20 to 29   
4  2019/10/01 12:39:20 PM GMT+8           Male  From 20 to 29   

  3. Are you currently....? 4. What is your annual income?  \
0                   Student             Less than RM25,000   
1                   Student             Less than RM25,000   
2                  Employed             Less than RM25,000   
3                   Student             Less than RM25,000   
4                   Student             Less than RM25,000   

  5. How often do you visit Starbucks? 6. How do you usually enjoy Starbucks?  \
0                               Rarely                                Dine in   
1                               Rarely                              Take away   
2                              Monthly                                Dine in   
3                               Rarely                              Take away   
4                              Monthly                              Take away   

  7. How much time do you normally  spend during your visit?  \
0                       Between 30 minutes to 1 hour           
1                                   Below 30 minutes           
2                       Between 30 minutes to 1 hour           
3                                   Below 30 minutes           
4                       Between 30 minutes to 1 hour           

  8. The nearest Starbucks's outlet to you is...?  \
0                                      within 1km   
1                                       1km - 3km   
2                                   more than 3km   
3                                   more than 3km   
4                                       1km - 3km   

  9. Do you have Starbucks membership card?  ...  \
0                                       Yes  ...   
1                                       Yes  ...   
2                                       Yes  ...   
3                                        No  ...   
4                                        No  ...   

  11. On average, how much would you spend at Starbucks per visit?  \
0                                     Less than RM20                 
1                                     Less than RM20                 
2                                     Less than RM20                 
3                                     Less than RM20                 
4                                 Around RM20 - RM40                 

  12. How would you rate the quality of Starbucks compared to other brands (Coffee Bean, Old Town White Coffee..) to be:  \
0                                                  4                                                                       
1                                                  4                                                                       
2                                                  4                                                                       
3                                                  2                                                                       
4                                                  3                                                                       

   13. How would you rate the price range at Starbucks?  \
0                                                  3      
1                                                  3      
2                                                  3      
3                                                  1      
4                                                  3      

   14. How important are sales and promotions in your purchase decision?  \
0                                                  5                       
1                                                  4                       
2    

In [99]:
null_value_stats = train_df.isnull().sum(axis=0)
null_value_stats[null_value_stats != 0]

6. How do you usually enjoy Starbucks?                                           1
19. How do you come to hear of promotions at Starbucks? Check all that apply.    1
dtype: int64

In [100]:
train_df.fillna(-999, inplace=True)

In [101]:
X = train_df.drop('20. Will you continue buying at Starbucks?', axis=1)
y = train_df['20. Will you continue buying at Starbucks?']

In [102]:
print(X.dtypes)

categorical_features_indices = np.where(X.dtypes != float)[0]

Timestamp                                                                                                                 object
1. Your Gender                                                                                                            object
2. Your Age                                                                                                               object
3. Are you currently....?                                                                                                 object
4. What is your annual income?                                                                                            object
5. How often do you visit Starbucks?                                                                                      object
6. How do you usually enjoy Starbucks?                                                                                    object
7. How much time do you normally  spend during your visit?                                       

In [103]:
from sklearn.model_selection import train_test_split

X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.75, random_state=42)

In [104]:
for i in [50, 60, 70, 80, 90, 100]:
    model = CatBoostClassifier(
        iterations=100,
        random_seed=i,
        logging_level='Silent',
        eval_metric=metrics.Accuracy()
    )
    model.fit(
        X_train, y_train,
        cat_features=categorical_features_indices,
        eval_set=(X_validation, y_validation),
    #     logging_level='Verbose',  # you can uncomment this for text output
        plot=True,
    );

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [96]:
model.fit(
    X_train, y_train,
    cat_features=categorical_features_indices,
    eval_set=(X_validation, y_validation),
#     logging_level='Verbose',  # you can uncomment this for text output
    plot=True,
);

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [25]:
predictions = model.predict(X_validation)
predictions_probs = model.predict_proba(X_validation)
print(predictions[:10])
print(predictions_probs[:10])

['Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes']
[[0.0556 0.9444]
 [0.0943 0.9057]
 [0.7814 0.2186]
 [0.2719 0.7281]
 [0.2152 0.7848]
 [0.1288 0.8712]
 [0.1343 0.8657]
 [0.6749 0.3251]
 [0.09   0.91  ]
 [0.1153 0.8847]]
